apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_HOSTS
              value: "postgres"
            - name: DATABASE_URI
              value: "postgresql://todo:todo@postgres:5432/todo?sslmode=disable"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"