version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: todo:latest
    environment:
      DATABASE_HOSTS: postgres
      DATABASE_URI: 'postgresql://todo:todo@postgres:5432/todo?sslmode=disable'
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: